"""Unit tests: one public docstring at a time, the source of the API reference.

Only functions and classes carry a docstring of their own. The exported
constants (AVAILABLE_DATASETS, REAL_DATASETS, MODEL_REGISTRY, DEFAULT_CONFIG)
are described by `.. data::` entries in the reference instead.
"""
from __future__ import annotations

import dataclasses
import inspect

import pytest

import hbsaemp
from tests.docs._pages import public_names

pytestmark = pytest.mark.docs


def _own_doc(obj: object) -> str:
    """The docstring written for *obj* itself, never one it inherits or is given."""
    doc = getattr(obj, "__doc__", None) or ""
    if inspect.isclass(obj) and dataclasses.is_dataclass(obj) and doc.startswith(f"{obj.__name__}("):
        return ""  # generated by @dataclass from the signature, not written
    return inspect.cleandoc(doc)


def _docstrings(obj: object) -> dict[str, str]:
    """The docstrings the reference renders for *obj*: its own and its public members'."""
    docs = {"": _own_doc(obj)}
    if inspect.isclass(obj):
        for attr, member in vars(obj).items():
            if attr.startswith("_"):
                continue
            target = member.fget if isinstance(member, property) else member
            target = getattr(target, "__func__", target)
            if inspect.isfunction(target):
                docs[attr] = _own_doc(target)
    return docs


DOCUMENTED = [n for n in public_names()
              if inspect.isclass(getattr(hbsaemp, n)) or inspect.isfunction(getattr(hbsaemp, n))]


@pytest.mark.parametrize("name", DOCUMENTED)
def test_public_object_has_a_summary_line(name: str) -> None:
    """autosummary shows the first docstring line; without one the entry is blank."""
    missing = [attr or name for attr, doc in _docstrings(getattr(hbsaemp, name)).items()
               if not doc.strip()]
    assert not missing, f"no docstring for {missing}"
